import type { PromptPreset } from '../types';

export const PROMPT_PRESETS: PromptPreset[] = [
  {
    id: 'preset-1',
    name: 'Noir Ballad',
    description: 'Monochromatic scenes with rain, city lights, and emotional close-ups',
    category: 'emotional',
    concept_prompt: 'Rain-soaked streets, neon reflections, a lone figure walking through fog, emotional depth, cinematic close-ups, shadow and light interplay',
    visual_style: 'noir',
    mood: 'melancholic',
    pacing: 'slow_contemplative',
    camera_language: 'fluid_handheld',
    editing_intensity: 'subtle',
    realism_level: 70,
    tags: ['noir', 'rain', 'emotional', 'urban'],
    is_featured: true,
    preview_image_url: null,
  },
  {
    id: 'preset-2',
    name: 'Hyper Cinematic',
    description: 'Epic wide shots, dramatic lighting, blockbuster production value',
    category: 'epic',
    concept_prompt: 'Vast landscapes, golden hour light, dramatic skies, sweeping camera movements, cinematic depth of field, epic scale',
    visual_style: 'cinematic',
    mood: 'epic',
    pacing: 'dynamic',
    camera_language: 'wide_epic',
    editing_intensity: 'standard',
    realism_level: 85,
    tags: ['epic', 'cinematic', 'landscape', 'dramatic'],
    is_featured: true,
    preview_image_url: null,
  },
  {
    id: 'preset-3',
    name: 'Neon Cyberpunk',
    description: 'Futuristic city, glowing neon, cyberpunk aesthetic, high energy',
    category: 'futuristic',
    concept_prompt: 'Neon-lit cyberpunk city, holographic displays, rain and reflections, chrome surfaces, futuristic fashion, electric atmosphere',
    visual_style: 'neon_cyberpunk',
    mood: 'dark_intense',
    pacing: 'rapid_cut',
    camera_language: 'mixed',
    editing_intensity: 'aggressive',
    realism_level: 40,
    tags: ['cyberpunk', 'neon', 'futuristic', 'city'],
    is_featured: true,
    preview_image_url: null,
  },
  {
    id: 'preset-4',
    name: 'Dream State',
    description: 'Soft focus, floating visuals, surreal transitions, ethereal beauty',
    category: 'abstract',
    concept_prompt: 'Dreamy soft focus, ethereal light, floating petals, slow morphing shapes, pastel hues blending into darkness, weightless motion',
    visual_style: 'abstract',
    mood: 'dreamy',
    pacing: 'slow_contemplative',
    camera_language: 'macro_intimate',
    editing_intensity: 'subtle',
    realism_level: 20,
    tags: ['dream', 'abstract', 'ethereal', 'surreal'],
    is_featured: false,
    preview_image_url: null,
  },
  {
    id: 'preset-5',
    name: 'Vintage Analog',
    description: 'Film grain, warm tones, Super 8 aesthetic, nostalgic feel',
    category: 'retro',
    concept_prompt: 'Super 8 film aesthetic, warm grain, light leaks, nostalgic summer memories, faded colors, analog imperfections, genuine moments',
    visual_style: 'vintage_film',
    mood: 'melancholic',
    pacing: 'moderate',
    camera_language: 'fluid_handheld',
    editing_intensity: 'standard',
    realism_level: 60,
    tags: ['vintage', 'film', 'nostalgic', 'analog'],
    is_featured: false,
    preview_image_url: null,
  },
  {
    id: 'preset-6',
    name: 'Minimal Control',
    description: 'Clean geometric forms, stark contrast, architectural precision',
    category: 'minimal',
    concept_prompt: 'Stark white and black geometric compositions, architectural lines, minimal movement, high contrast shadows, pure form and space',
    visual_style: 'minimal_clean',
    mood: 'introspective',
    pacing: 'moderate',
    camera_language: 'static_composed',
    editing_intensity: 'subtle',
    realism_level: 50,
    tags: ['minimal', 'geometric', 'clean', 'architectural'],
    is_featured: false,
    preview_image_url: null,
  },
];

export const VISUAL_STYLE_LABELS: Record<string, string> = {
  cinematic: 'Cinematic',
  noir: 'Noir',
  neon_cyberpunk: 'Neon Cyberpunk',
  minimal_clean: 'Minimal Clean',
  documentary: 'Documentary',
  abstract: 'Abstract',
  vintage_film: 'Vintage Film',
  hyper_real: 'Hyper Real',
  anime: 'Anime',
  oil_painting: 'Oil Painting',
};

export const MOOD_LABELS: Record<string, string> = {
  epic: 'Epic',
  melancholic: 'Melancholic',
  euphoric: 'Euphoric',
  dark_intense: 'Dark & Intense',
  dreamy: 'Dreamy',
  aggressive: 'Aggressive',
  romantic: 'Romantic',
  mysterious: 'Mysterious',
  uplifting: 'Uplifting',
  introspective: 'Introspective',
};

export const PACING_LABELS: Record<string, string> = {
  slow_contemplative: 'Slow / Contemplative',
  moderate: 'Moderate',
  dynamic: 'Dynamic',
  rapid_cut: 'Rapid Cut',
  beat_synced: 'Beat Synced',
};

export const CAMERA_LABELS: Record<string, string> = {
  static_composed: 'Static / Composed',
  fluid_handheld: 'Fluid Handheld',
  drone_aerial: 'Drone / Aerial',
  macro_intimate: 'Macro / Intimate',
  wide_epic: 'Wide / Epic',
  mixed: 'Mixed',
};

export const EDITING_LABELS: Record<string, string> = {
  subtle: 'Subtle',
  standard: 'Standard',
  aggressive: 'Aggressive',
  experimental: 'Experimental',
};
