import type { PromptPreset } from '../types';

export const PROMPT_PRESETS: PromptPreset[] = [
  {
    id: 'preset-dark-cinematic',
    name: 'Dark Cinematic',
    description: 'Anamorphic framing, teal-orange grade, restrained precision',
    category: 'cinematic',
    concept_prompt: 'Vast landscapes, golden hour light, dramatic skies, sweeping compositions, cinematic depth of field, epic and restrained',
    visual_style: 'cinematic',
    mood: 'epic',
    pacing: 'dynamic',
    camera_language: 'wide_epic',
    shot_language: 'cinematic_slow_push',
    editing_intensity: 'standard',
    cinematic_mode: 'cinematic',
    realism_level: 85,
    negative_prompt: 'amateur, low quality, overexposed, grain, noise',
    tags: ['cinematic', 'landscape', 'dramatic', 'anamorphic'],
    is_system: true,
    is_featured: true,
    preview_image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'preset-luxury-performance',
    name: 'Luxury Performance',
    description: 'Immaculate production. Warm grade. Static and slow-push only.',
    category: 'luxury',
    concept_prompt: 'Immaculate luxury setting, artist in polished environment, warm natural light, clean surfaces, editorial restraint, presence and authority',
    visual_style: 'minimal_clean',
    mood: 'introspective',
    pacing: 'slow_contemplative',
    camera_language: 'static_composed',
    shot_language: 'static_luxury_frame',
    editing_intensity: 'subtle',
    cinematic_mode: 'luxury_brand',
    realism_level: 100,
    negative_prompt: 'grain, noise, motion blur, artifacts, casual, overexposed, saturated',
    tags: ['luxury', 'performance', 'editorial', 'static'],
    is_system: true,
    is_featured: true,
    preview_image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'preset-neon-dreamscape',
    name: 'Neon Dreamscape',
    description: 'Cyberpunk atmosphere, electric color, high energy cuts',
    category: 'neon',
    concept_prompt: 'Neon-lit cyberpunk city, holographic displays, rain and reflections, chrome surfaces, electric atmosphere, futuristic and visceral',
    visual_style: 'neon_cyberpunk',
    mood: 'dark_intense',
    pacing: 'rapid_cut',
    camera_language: 'mixed',
    shot_language: 'editorial_motion',
    editing_intensity: 'aggressive',
    cinematic_mode: 'stylized_concept',
    realism_level: 40,
    negative_prompt: 'boring composition, flat lighting, amateur',
    tags: ['cyberpunk', 'neon', 'futuristic', 'electric'],
    is_system: true,
    is_featured: true,
    preview_image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'preset-urban-editorial',
    name: 'Urban Editorial',
    description: 'Street-level energy, magazine photography, confident cuts',
    category: 'urban',
    concept_prompt: 'Urban street scenes, dynamic angles, street photography energy, sharp contrasts, city texture, authentic movement',
    visual_style: 'documentary',
    mood: 'aggressive',
    pacing: 'beat_synced',
    camera_language: 'fluid_handheld',
    shot_language: 'editorial_motion',
    editing_intensity: 'aggressive',
    cinematic_mode: 'editorial_montage',
    realism_level: 70,
    negative_prompt: 'overproduced, generic, low quality, amateur',
    tags: ['urban', 'editorial', 'street', 'documentary'],
    is_system: true,
    is_featured: true,
    preview_image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'preset-minimal-performance',
    name: 'Minimal Performance Cut',
    description: 'Clean motion, zero artifact, contemporary commercial',
    category: 'minimal',
    concept_prompt: 'Minimalist performance setting, clean backgrounds, precise movement, neutral palette, contemporary and controlled',
    visual_style: 'minimal_clean',
    mood: 'introspective',
    pacing: 'moderate',
    camera_language: 'static_composed',
    shot_language: 'performance_close_up',
    editing_intensity: 'subtle',
    cinematic_mode: 'clean_motion',
    realism_level: 95,
    negative_prompt: 'clutter, noise, grain, motion blur, surreal, artifacts',
    tags: ['minimal', 'performance', 'clean', 'contemporary'],
    is_system: true,
    is_featured: false,
    preview_image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'preset-high-emotion-narrative',
    name: 'High Emotion Narrative',
    description: 'Handheld intimacy, emotional performance, rain and light',
    category: 'narrative',
    concept_prompt: 'Rain-soaked streets, neon reflections, emotional close-ups, shadow and light interplay, raw authenticity, a figure navigating solitude',
    visual_style: 'noir',
    mood: 'melancholic',
    pacing: 'slow_contemplative',
    camera_language: 'fluid_handheld',
    shot_language: 'handheld_intimate',
    editing_intensity: 'subtle',
    cinematic_mode: 'cinematic',
    realism_level: 75,
    negative_prompt: 'overexposed, generic, stock footage feel, amateur, blurry',
    tags: ['narrative', 'emotional', 'noir', 'intimate'],
    is_system: true,
    is_featured: true,
    preview_image_url: null,
    created_at: new Date().toISOString(),
  },
];

// ─── Label Maps ───────────────────────────────────────────────────────────────

export const VISUAL_STYLE_LABELS: Record<string, string> = {
  cinematic: 'Cinematic',
  noir: 'Noir',
  neon_cyberpunk: 'Neon Cyberpunk',
  minimal_clean: 'Minimal Clean',
  documentary: 'Documentary',
  abstract: 'Abstract',
  vintage_film: 'Vintage Film',
  hyper_real: 'Hyper Real',
  anime: 'Anime',
  oil_painting: 'Oil Painting',
};

export const MOOD_LABELS: Record<string, string> = {
  epic: 'Epic',
  melancholic: 'Melancholic',
  euphoric: 'Euphoric',
  dark_intense: 'Dark / Intense',
  dreamy: 'Dreamy',
  aggressive: 'Aggressive',
  romantic: 'Romantic',
  mysterious: 'Mysterious',
  uplifting: 'Uplifting',
  introspective: 'Introspective',
};

export const PACING_LABELS: Record<string, string> = {
  slow_contemplative: 'Slow',
  moderate: 'Moderate',
  dynamic: 'Dynamic',
  rapid_cut: 'Rapid Cut',
  beat_synced: 'Beat Synced',
};

export const CAMERA_LABELS: Record<string, string> = {
  static_composed: 'Static',
  fluid_handheld: 'Handheld',
  drone_aerial: 'Aerial',
  macro_intimate: 'Macro',
  wide_epic: 'Wide Epic',
  mixed: 'Mixed',
};

export const EDITING_LABELS: Record<string, string> = {
  subtle: 'Subtle',
  standard: 'Standard',
  aggressive: 'Aggressive',
  experimental: 'Experimental',
};

export const CINEMATIC_MODE_LABELS: Record<string, string> = {
  cinematic: 'Cinematic',
  clean_motion: 'Clean Motion',
  editorial_montage: 'Editorial Montage',
  stylized_concept: 'Stylized Concept',
  luxury_brand: 'Luxury Brand',
};

export const SHOT_LANGUAGE_LABELS: Record<string, string> = {
  handheld_intimate: 'Handheld Intimate',
  cinematic_slow_push: 'Cinematic Slow Push',
  static_luxury_frame: 'Static Luxury Frame',
  performance_close_up: 'Performance Close-Up',
  wide_atmospheric: 'Wide Atmospheric',
  editorial_motion: 'Editorial Motion',
  drone_survey: 'Drone Survey',
  rack_focus_portrait: 'Rack Focus Portrait',
};
